```{r load custom themes, echo = FALSE, message = FALSE, eval=FALSE}
knitr::opts_chunk$set(message = FALSE, warning = FALSE)
```

```{r load packages, message=FALSE, warning=FALSE}
library(tidyverse)
library(dataedu)
library(lubridate)
library(here)
```

```{r demo here, eval = FALSE}
here::here("Aggregate & Longitudinal Analysis",
            "data",
           "longitudinal_data",
           "bchildcountandedenvironments2012.csv")
```


```{r read 2012 data with skip, warning = FALSE, message = FALSE}
read_csv(here::here(
  "Aggregate &  Longitudinal Analysis",
  "data",
  "longitudinal_data",
  "bchildcountandedenvironments2012.csv"
),
skip = 4)
```

```{r get filenames, results='hide'}
# Get filenames from the data folder 
filenames <-
  list.files(path = here::here("Aggregate &  Longitudinal Analysis", "data", "longitudinal_data"),
             full.names = TRUE)

# A list of filenames and paths
filenames
```


```{r read list of CSVs, , message=FALSE, warning=FALSE}
# Pass filenames to map and read_csv
all_files <-
  filenames %>%
  # Apply the function read_csv to each element of filenames
  map(., ~ read_csv(., skip = 4))
```


```{r combine datasets 1}
# combining the datasets at this stage results in the incorrect 
# number of columns
bind_rows(all_files) %>% 
  # check the number of columns
  ncol()

```

```{r fix 2016 colnames, message=FALSE, warning=FALSE}
all_files[[5]] <-
  # Skip the first 3 lines instead of the first 4
  read_csv(filenames[[5]], skip = 3)

print(all_files)
```

```{r pick vars on data 2012}
all_files[[1]] %>%
  select(
    Year,
    contains("State", ignore.case = FALSE),
    contains("SEA", ignore.case = FALSE),
    contains("American"),
    contains("Asian"),
    contains("Black"),
    contains("Hispanic"),
    contains("Native"),
    contains("Two"),
    contains("White")
  ) 

```

```{r pick vars function on other data sets}
# build the function
pick_vars <-
  function(df) {
    df %>%
      select_at(vars(
        Year,
        contains("State", ignore.case = FALSE),
        contains("SEA", ignore.case = FALSE),
        contains("American"),
        contains("Asian"),
        contains("Black"),
        contains("Hispanic"),
        contains("Native"),
        contains("Two"),
        contains("White")
      ))
  }

# use the function with `all_files`
all_files <-
  all_files %>%
  map(pick_vars)
```

```{r verify var names}
# check variable names
all_files %>% 
  map(names)
```
```{r combine datasets 2}
race_counts <-
  all_files %>%
  # combine all datasets in `all_files`
  bind_rows()

print(race_counts)
```
```{r filter child_counts}
race_counts <-
  race_counts %>%
  filter(
    # filter all but the All Disabilities category
    `SEA Disability Category` == "All Disabilities",
    # filter all but the age totals
    `SEA Education Environment` %in% c("Total, Age 3-5", "Total, Age 6-21")
  ) 
print(race_counts)
```
```{r rename vars}
race_counts <-
  race_counts %>%
  rename(
    # change these columns to more convenient names
    year = Year,
    state = "State Name",
    age = "SEA Education Environment",
    disability = "SEA Disability Category",
    aian_3_5 = "American Indian or Alaska Native Age 3 to 5",
    aian_6_21 = "American Indian or Alaska Native Age 6 to21",
    aa_3_5 = "Black or African American Age 3-5",
    aa_6_21 = "Black or African American Age 6 to21",
    as_3_5 = "Asian Age 3-5",
    as_6_21 = "Asian Age 6 to21",
    hi_3_5 = "Hispanic/Latino Age 3-5",
    hi_6_21 = "Hispanic/Latino Age 6 to21",
    nhpi_3_5 = "Native Hawaiian or Other Pacific Islander Age 3-5",
    nhpi_6_21 = "Native Hawaiian or Other Pacific Islander Age 6 to21",
    mixed_3_5 = "Two or More Races Age 3-5",
    mixed_6_21 = "Two or more races Age 6 to21",
    wh_3_5 = "White Age 3-5",
    wh_6_21 = "White Age 6 to21" 
  )
```
```{r}
print(race_counts)
```

```{r fix caps}
race_counts <-
  race_counts %>%
  mutate(state = tolower(state)) 
```


```{r pivot_longer race col}
race_counts <-
  race_counts %>%
    pivot_longer(cols = aian_3_5:wh_6_21, 
                 names_to = "race", 
                 values_to = "total")
```

Combine the age groups together because we don't need that for our RQ. 
```{r replace race values}
race_counts <- 
  race_counts %>%
  mutate(
    race = case_when(
      race == "aian_3_5" ~ "aian",
      race == "aa_3_5" ~ "aa",
      race == "as_3_5" ~ "as",
      race == "hi_3_5" ~ "hi",
      race == "nhpi_3_5" ~ "nhpi",
      race == "mixed_3_5" ~ "mixed",
      race == "wh_3_5" ~ "wh",
      race == "aian_6_21" ~ "aian",
      race == "aa_6_21" ~ "aa",
      race == "as_6_21" ~ "as",
      race == "hi_6_21" ~ "hi",
      race == "nhpi_6_21" ~ "nhpi",
      race == "mixed_6_21" ~ "mixed",
      race == "wh_6_21" ~ "wh",
    
      TRUE ~ as.character(race)
    )
  )
```

```{r convert to numeric}
race_counts <-
  race_counts %>%
  mutate(total = as.numeric(total))

race_counts
```

```{r convert date}
race_counts <-
  race_counts %>%
  mutate(year = ymd(year, truncated = 2))
```

```{r show NAs}
race_counts %>%
  arrange(year, state, race)
```

```{r remove NAs}
race_counts <-
  race_counts %>%
  filter(!is.na(total)) 
```

```{r verify rows}
race_counts %>%
  arrange(year, state, race)
```

## RQ: What is the ethnic composition of disabled children all over the USA over time? 

Since we don't care about individual states, we sum up the number of disabled children in all over states to get a nationwide figure.
```{r}
library(dplyr)

race_counts_nationwide <- race_counts %>%
  # Filter rows for the two specified age groups
  filter(age %in% c("Total, Age 3-5", "Total, Age 6-21")) %>%
  # Group by year, state, race
  group_by(year, race) %>%
  # Sum the 'total' column for each group
  summarise(total_disabled = sum(total))

# View the resulting dataset
head(race_counts_nationwide)
```
```{r calculate percentage}
# Calculate the percentage of disabled children for each ethnic group in each year
race_counts_nationwide <- race_counts_nationwide %>%
  group_by(year) %>%
  mutate(percentage = total_disabled / sum(total_disabled) * 100)

# View the resulting dataset
head(race_counts_nationwide)
```
```{r}
library(ggplot2)

# Assuming your dataset is named 'your_dataset'
ggplot(race_counts_nationwide, aes(x = year, y = percentage, fill = race)) +
  geom_bar(stat = "identity", position = "stack") +
  geom_text(aes(label = scales::percent(percentage/100), 
                y = percentage), 
            position = position_stack(vjust = 0.5), 
            size = 3) +
  scale_fill_manual(values = c(aa = "blue", aian = "green", as = "red", 
                                hi = "purple", mixed = "orange", nhpi = "yellow", 
                                wh = "gray")) + 
  labs(title = "Ethnic Composition of Disabled Children Over Time",
       x = "Year", y = "Percentage of Disabled Children") +
  theme_minimal()

```
